version: '2'
services:
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: data
    ports:
      - 80:80 # Expose http and https
      - 443:443
    networks:
      - wpdkr
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - ./db-init:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: data
    networks:
      - wpdkr
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: data
    networks:
      - wpdkr
networks:
  wpdkr: